name: ESPHome Proxy
version: "1.2"
panel_icon: "mdi:chip"
panel_title: ESPHome Proxy
slug: esphome-proxy
description: Proxy addon for ESPHome
url: "https://github.com/esphome"
startup: application
boot: auto
ingress: true
ingress_port: 6052
ingress_entry: /
panel_admin: false
host_network: false
devices: []
usb: false
tmpfs: false
full_access: false
environment: {}
options:
  server: "http://esphome.local:6052"
  proxy_pass_host: true
  proxy_pass_real_ip: true
schema:
  server: "match(^https?://.+:\\d+$)"
  proxy_pass_host: bool
  proxy_pass_real_ip: bool
services: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
