name: go2rtc Proxy
version: "1.0"
panel_icon: "mdi:eye"
panel_title: go2rtc
slug: go2rtc-proxy
description: Proxy addon for go2rtc
url: "https://github.com/AlexxIT/go2rtc/tree/master"
startup: application
boot: auto
webui: "http://[HOST]:[PORT:1984]/"
watchdog: "http://[HOST]:[PORT:1984]/"
ingress: true
ingress_port: 1984
ingress_entry: /
panel_admin: false
ports:
  1984/tcp: 1984
ports_description:
  1984/tcp: Web interface (Not required for Hass.io Ingress)
host_network: false
devices: []
usb: false
tmpfs: false
full_access: false
environment: {}
options:
  server: "http://go2rtc.local:1984"
  proxy_pass_host: true
  proxy_pass_real_ip: true
schema:
  server: "match(^https?://.+:\\d+$)"
  proxy_pass_host: bool
  proxy_pass_real_ip: bool
services: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
